export const tasks = [
    {"id" : "dispatch-event",
    "title" : "Dispatch Event",
    "description" :"Create an event and dispatch it to the queue to pass on to the proper event handler." },
    {"id" : "event-handling",
    "title" : "Handle Event",
    "description" : "Receive event from dispatch and change app state. Return an effect."},
    {"id" : "effect-handler",
    "title" : "Effect Handler",
    "description" : "Receive effect from even handler and update app state"},
    {"id" : "query-function",
    "title" : "Query Function",
    "description" : "Watch for app state on specific query id. Once change occurs, pull new value from app state."},
    {"id" : "update-view",
    "title" : "Update View",
    "description" : "Subsription watches for query function to run, receives new value and updates the view."},
    {"id" : "update-dom",
    "title" : "Update DOM",
    "description" : "Receives updated view from view funciton and uses this to update the DOM."}
]
